services:
  webserver:
    container_name: library-loans-nginx
    restart: on-failure
    image: 'nginx:alpine'
    ports:
      - '8000:80'
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './public:/application/public'

  php-fpm:
    container_name: library-loans-php-fpm
    restart: on-failure
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: development
    volumes:
      - '.:/application'
    working_dir: /application
    environment:
      XDEBUG_MODE: 'debug,develop'
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
  db:
    container_name: library-loans-db
    image: mysql
    volumes:
        - './mysql_volume:/var/lib/mysql'
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_USER: user
        MYSQL_PASSWORD: 1234
    ports:
        - '33066:3306'
  phpmyadmin:
    depends_on:
        - db
    container_name: library-loans-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - '8001:80'
    environment:
        - PMA_ARBITRARY=1
        - UPLOAD_LIMIT=300000000
        - MYSQL_ROOT_PASSWORD=1234
        - PMA_HOST=db
